# https://docs.readthedocs.io/en/latest/config-file/v2.html
version: 2

formats:
  - htmlzip
  - epub

build:
  image: latest

sphinx:
  configuration: docs/source/conf.py
  fail_on_warning: true

python:
  version: 3.8
  install:
    - method: pip
      path: .
      extra_requirements:
        - p_docs
